### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by jvandriel** [giuliopons/bright-link-previews#13]
I've recently started using Bright Link Previews and am wondering a few things:

- What has the cache lifetime been set to, a fixed period or indefinitely?
- Is there a difference between mobile vs. desktop cache, or is it all just the same cache?
- Sometimes links don't generate a preview on mobile (just says 'loading') but do on desktop, as well as vice versa. Any idea why this might be happening?
- Sometimes when hovering over a link the preview shows the content of another link. Any idea what could be the cause for this and how to fix it?
- There's one particular Wikipedia link to [Schrödinger's cat](https://en.wikipedia.org/wiki/Schr%C3%B6dinger's_cat) that generates a 404 preview, yet when I follow that link the page has a status 200. This could, theoretically, be a joke created at Wikipedia's end though before presuming that's the case I just have to ask. Have you got any idea what's going on here?
<img width="389" alt="schrodingers-cat" src="https://github.com/giuliopons/bright-link-previews/assets/7320889/30eb6c58-2b0c-4749-bcd5-7721cc55d61e">

**Comment by giuliopons** [comment]
The cache is 72 hours.
The cache is the same for desktop and mobile.


> Sometimes links don't generate a preview on mobile (just says 'loading') but do on desktop, as well as vice versa. Any idea why this might be happening?

This is probably a bug.

> Sometimes when hovering over a link the preview shows the content of another link. Any idea what could be the cause for this and how to fix it?

This is probably a bug too.

> There's one particular Wikipedia link to [Schrödinger's cat](https://en.wikipedia.org/wiki/Schr%C3%B6dinger's_cat) that generates a 404 preview, yet when I follow that link the page has a status 200. This could, theoretically, be a joke created at Wikipedia's end though before presuming that's the case I just have to ask. Have you got any idea what's going on here?

I will check this particular link to understand why this strange behaviour happens.

**Comment by giuliopons** [comment]
Please @jvandriel try with the new 1.7 version and let me no if the problem with the Schrodinger's cat has been solved.

**Comment by jvandriel** [comment]
The 1.7 version didn't resolve the issue with schrödinger's cat. Although I am really hoping this has nothing to do with the plugin and everything with Wikipedia as the 'error' wonderfully illustrates the paradox the page describes.

**Comment by jvandriel** [comment]
I just noticed the new 1.7 version is causing issues preventing WP (6.4.3) jQuery lightbox from working, though I'm not sure whether anything else gets influenced by it as well. I just noticed this since I make use of the lightbox. Chrome's console output shows this:

<img width="500" alt="Screen Shot 2024-02-05 at 9 07 24 PM" src="https://github.com/giuliopons/bright-link-previews/assets/7320889/a8bf85d7-602b-41dd-b71e-5ee79f27254a">

**Comment by giuliopons** [comment]
> I just noticed the new 1.7 version is causing issues preventing WP (6.4.3) jQuery lightbox from working, though I'm not sure whether anything else gets influenced by it as well. I just noticed this since I make use of the lightbox. Chrome's console output shows this:
> 
> <img alt="Screen Shot 2024-02-05 at 9 07 24 PM" width="500" src="https://private-user-images.githubusercontent.com/7320889/302415789-a8bf85d7-602b-41dd-b71e-5ee79f27254a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1MTE3NjEsIm5iZiI6MTcwNzUxMTQ2MSwicGF0aCI6Ii83MzIwODg5LzMwMjQxNTc4OS1hOGJmODVkNy02MDJiLTQxZGQtYjcxZS01ZWU3OWYyNzI1NGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDlUMjA0NDIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmU4ZmNiYTFmN2FjZWQxZjU2YTFlZmIzODhkMzliNWExMTJmMjllODYxNzg1Nzk1ODNiNDAzMGI3NGQ2MDYzMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iywj4xqaW76uKU22QtG26bcdw3govX4QBTICAy0M2Gg">

Are you sure that this problem is related to my plugin?

**Comment by giuliopons** [comment]
I've fixed the problem with the Schrödinger's cat. Next update will include this fix.

**Comment by jvandriel** [comment]
Well, when I turn the plugin off the JS errors are gone and the pightbox works again. That"s about at certain as I'm able to be.

**Comment by giuliopons** [comment]
Please send me the exact url to see the error.

(Meanwhile I've also fixed the HTML tags, now there aren't heading tags anymore)

**Comment by jvandriel** [comment]
You can see it here: https://invisiblegraph.com/semantic-stories/does-structured-data-markup-influence-eeat/

**Comment by giuliopons** [comment]
Try to install the new 1.81 version and tell me if it solves the problem (I haven't understood it)

**Comment by jvandriel** [comment]
The cat-link now works. Adjusted my CSS to accommodate the new HTML element, which also works great. The previews also seem to preview faster/more consistently but unfortunately, the JS error persists.

If I turn BLP off all the jQuery lightboxes work, though when I turn it on (as now), one can't enlarge the images in the story.

**Comment by giuliopons** [comment]
Mmm can you send me an ftp access? I'd like to make some test on your installation to understand which part of my code cause the conflict.

**Comment by jvandriel** [comment]
I've sent you an email.

**Comment by giuliopons** [comment]
bug fixed!

**Comment by jvandriel** [comment]
Thank you very much again. I've just made a donation to show my appreciation.

**Comment by giuliopons** [comment]
Thank you!

Il giorno sab 10 feb 2024 alle ore 21:01 Jarno van Driel <
***@***.***> ha scritto:

> Thank you very much again. I've just made a donation to show my
> appreciation.
>
> With kind regards,
> Jarno
>
